### ISSUE TITLE
Cannot perform POST x-www-form request (using deprecated code)

### ISSUE THREAD

**Issue by didlidu** [bunjlabs/Fuga-Framework#2]

**Comment by Show-vars** [comment]
Yep, that problem was fixed but anyway we must refactor everything about http server and remove all netty's deprecated classes including cookies, form-data parser and so on.

**Comment by didlidu** [comment]
shouldn't this issue be closed?

**Comment by Show-vars** [comment]
Oh yes of course.

Actually this issue should be tagged as `feature request` because this version of fuga only used in old projects that will never depends on x-www-form POST requests. The next version of fuga uses a jetty http implementation, so everything that regarding HTTP has no bugs at all (except jetty bugs).
